# -*- coding: utf-8 -*-
"""Task2_Hindi_Finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mJ15S0xZGXl3FhhwVoU-Ak7fomk311D1
"""

!pip install -q unsloth
!pip install -q transformers datasets trl peft accelerate bitsandbytes

from google.colab import drive
drive.mount('/content/drive')

from datasets import load_dataset

dataset = load_dataset(
    "json",
    data_files = "/content/drive/MyDrive/Task2_Hindi/dataset_clean.jsonl",
    split = "train"
)

print(f"Total examples: {len(dataset)}")

from unsloth import FastLanguageModel
import torch

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "sarvamai/sarvam-1",
    max_seq_length = 512,
    dtype = torch.float16,
    load_in_4bit = True,
)

print("Model loaded successfully")
print(f"Parameters: {model.num_parameters():,}")

model = FastLanguageModel.get_peft_model(
    model,
    r = 16,
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj"],
    lora_alpha = 32,
    lora_dropout = 0.05,
    bias = "none",
    use_gradient_checkpointing = "unsloth",
    random_state = 42,
)

model.print_trainable_parameters()

def format_example(example):
    messages = example["messages"]
    system    = messages[0]["content"]
    user      = messages[1]["content"]
    assistant = messages[2]["content"]
    text = (
        f"### System:\n{system}\n\n"
        f"### User:\n{user}\n\n"
        f"### Assistant:\n{assistant}"
    )
    return {"text": text}

dataset = dataset.map(format_example, remove_columns=dataset.column_names)

split1 = dataset.train_test_split(test_size=0.2, seed=42)
split2 = split1["test"].train_test_split(test_size=0.5, seed=42)

train_dataset = split1["train"]
eval_dataset  = split2["train"]
test_dataset  = split2["test"]

print(f"Train      : {len(train_dataset)}")
print(f"Validation : {len(eval_dataset)}")
print(f"Test       : {len(test_dataset)}")
print(f"\nSample:")
print(train_dataset[0]["text"][:300])

from trl import SFTTrainer
from transformers import TrainingArguments
from unsloth import is_bfloat16_supported

training_args = TrainingArguments(
    output_dir = "outputs",
    per_device_train_batch_size = 2,
    gradient_accumulation_steps = 8,
    num_train_epochs = 3,
    learning_rate = 1e-4,
    lr_scheduler_type = "cosine",
    warmup_steps = 20,
    weight_decay = 0.01,
    max_grad_norm = 0.3,
    fp16 = not is_bfloat16_supported(),
    bf16 = is_bfloat16_supported(),
    logging_steps = 10,
    eval_strategy = "steps",
    eval_steps = 50,
    save_strategy = "no",
    optim = "adamw_8bit",
    seed = 42,
    report_to = "none",
)

trainer = SFTTrainer(
    model = model,
    processing_class = tokenizer,
    train_dataset = train_dataset,
    eval_dataset = eval_dataset,
    dataset_text_field = "text",
    max_seq_length = 512,
    args = training_args,
)

print("Starting training...")
trainer_stats = trainer.train()
print(f"\nTraining complete")
print(f"Total steps : {trainer_stats.global_step}")
print(f"Final loss  : {trainer_stats.training_loss:.4f}")

save_path = "/content/drive/MyDrive/Task2_Hindi/sarvam_adapter"
model.save_pretrained(save_path)
tokenizer.save_pretrained(save_path)
print(f"Saved to {save_path}")

FastLanguageModel.for_inference(model)

def generate(prompt, max_new_tokens=256):
    text = (
        f"### System:\nतुम एक सहायक हिन्दी भाषा के सहायक हो।\n\n"
        f"### User:\n{prompt}\n\n"
        f"### Assistant:\n"
    )
    inputs = tokenizer(
        text,
        return_tensors = "pt",
        truncation = True,
        max_length = 512
    ).to("cuda")

    outputs = model.generate(
        input_ids = inputs["input_ids"],
        attention_mask = inputs["attention_mask"],
        max_new_tokens = max_new_tokens,
        temperature = 0.3,
        top_p = 0.85,
        top_k = 50,
        repetition_penalty = 1.15,
        do_sample = True,
        pad_token_id = tokenizer.eos_token_id
    )

    response = tokenizer.decode(
        outputs[0][len(inputs["input_ids"][0]):],
        skip_special_tokens = True
    ).strip()
    return response

test_prompts = [
    "भारत का सबसे बड़ा रेगिस्तान कौन सा है?",
    "दोस्त से झगड़ा हो जाए तो क्या करें?",
    "एक किसान के पास 120 आम हैं। वह उन्हें 8 टोकरियों में बराबर बाँटता है। हर टोकरी में कितने आम होंगे?",
    "सुबह जल्दी उठने की आदत कैसे डालें?",
    "नमस्ते कहने के अलावा हिंदी में अभिवादन के और क्या तरीके हैं?"
]

print("=" * 60)
for i, prompt in enumerate(test_prompts):
    print(f"\nप्रश्न {i+1}: {prompt}")
    print("-" * 40)
    print(f"उत्तर: {generate(prompt)}")
    print("=" * 60)

import warnings
import logging
warnings.filterwarnings("ignore")
logging.getLogger("transformers").setLevel(logging.ERROR)

from unsloth import FastLanguageModel
import torch

# load base model
base_model, base_tokenizer = FastLanguageModel.from_pretrained(
    model_name = "sarvamai/sarvam-1",
    max_seq_length = 512,
    dtype = torch.float16,
    load_in_4bit = True,
)
FastLanguageModel.for_inference(base_model)

def generate_from(mdl, tok, prompt, max_new_tokens=256):
    text = (
        f"### System:\nतुम एक सहायक हिन्दी भाषा के सहायक हो।\n\n"
        f"### User:\n{prompt}\n\n"
        f"### Assistant:\n"
    )
    inputs = tok(
        text,
        return_tensors = "pt",
        truncation = True,
        max_length = 512
    ).to("cuda")

    outputs = mdl.generate(
        input_ids = inputs["input_ids"],
        attention_mask = inputs["attention_mask"],
        max_new_tokens = max_new_tokens,
        temperature = 0.3,
        top_p = 0.85,
        top_k = 50,
        repetition_penalty = 1.15,
        do_sample = True,
        pad_token_id = tok.eos_token_id
    )
    return tok.decode(
        outputs[0][len(inputs["input_ids"][0]):],
        skip_special_tokens = True
    ).strip()

# 5 test prompts covering all domains
test_prompts = [
    "महात्मा गांधी के बारे में बताइए।",
    "भारत का सबसे बड़ा रेगिस्तान कौन सा है?",
    "सुबह जल्दी उठने की आदत कैसे डालें?",
    "एक किसान के पास 120 आम हैं। वह उन्हें 8 टोकरियों में बराबर बाँटता है। हर टोकरी में कितने आम होंगे?",
    "दोस्त से झगड़ा हो जाए तो क्या करें?",
]

# store responses for Cell 10
base_responses = []
ft_responses = []

print("=" * 70)
print("         BASE MODEL vs FINE-TUNED MODEL COMPARISON")
print("=" * 70)

for i, prompt in enumerate(test_prompts):
    print(f"\nप्रश्न {i+1}: {prompt}")
    print("-" * 70)

    base_resp = generate_from(base_model, base_tokenizer, prompt)
    ft_resp   = generate(prompt)

    base_responses.append(base_resp)
    ft_responses.append(ft_resp)

    print(f"❌ BASE MODEL:\n{base_resp}")
    print(f"\n✅ FINE-TUNED MODEL:\n{ft_resp}")
    print("=" * 70)

print("\nComparison complete. Run Cell 10 for metrics.")

import warnings
import logging
warnings.filterwarnings("ignore")
logging.getLogger("transformers").setLevel(logging.ERROR)

from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
import nltk
import numpy as np
nltk.download("punkt", quiet=True)

smoothing = SmoothingFunction().method1
base_bleu_scores = []
ft_bleu_scores   = []
base_lengths     = []
ft_lengths       = []

print("Calculating metrics on 30 held-out test examples...")
print("Please wait...\n")

for example in test_dataset.select(range(min(30, len(test_dataset)))):
    text = example["text"]
    parts = text.split("### Assistant:\n")
    if len(parts) < 2:
        continue

    reference = parts[1].strip()
    user_part = parts[0].split("### User:\n")[-1].split("\n\n")[0].strip()

    base_hyp = generate_from(base_model, base_tokenizer, user_part)
    ft_hyp   = generate(user_part)

    ref_tokens  = list(reference)
    base_tokens = list(base_hyp)
    ft_tokens   = list(ft_hyp)

    if base_tokens:
        base_bleu_scores.append(
            sentence_bleu([ref_tokens], base_tokens, smoothing_function=smoothing)
        )
        base_lengths.append(len(base_hyp.split()))

    if ft_tokens:
        ft_bleu_scores.append(
            sentence_bleu([ref_tokens], ft_tokens, smoothing_function=smoothing)
        )
        ft_lengths.append(len(ft_hyp.split()))

# compute metrics
avg_base_bleu  = np.mean(base_bleu_scores) if base_bleu_scores else 0
avg_ft_bleu    = np.mean(ft_bleu_scores)   if ft_bleu_scores   else 0
bleu_improve   = ((avg_ft_bleu - avg_base_bleu) / avg_base_bleu * 100) if avg_base_bleu > 0 else 0

avg_base_len   = np.mean(base_lengths) if base_lengths else 0
avg_ft_len     = np.mean(ft_lengths)   if ft_lengths   else 0

base_empty     = sum(1 for r in base_responses if len(r.strip()) < 10)
ft_empty       = sum(1 for r in ft_responses   if len(r.strip()) < 10)

print("=" * 70)
print("              QUANTITATIVE EVALUATION RESULTS")
print("=" * 70)
print(f"\n{'Metric':<35} {'Base Model':>15} {'Fine-tuned':>15}")
print("-" * 70)
print(f"{'BLEU Score (avg)':<35} {avg_base_bleu:>15.4f} {avg_ft_bleu:>15.4f}")
print(f"{'BLEU Improvement':<35} {'—':>15} {f'+{bleu_improve:.1f}%':>15}")
print(f"{'Avg response length (words)':<35} {avg_base_len:>15.1f} {avg_ft_len:>15.1f}")
print(f"{'Empty/incoherent responses':<35} {base_empty:>15} {ft_empty:>15}")
print(f"{'Test examples evaluated':<35} {len(base_bleu_scores):>15} {len(ft_bleu_scores):>15}")
print("=" * 70)

print(f"""
INTERPRETATION:
- BLEU score measures how similar generated text is to reference answers
- Higher BLEU = closer to expected Hindi responses
- Fine-tuned model improved by {bleu_improve:.1f}% over base model
- Longer responses indicate the model learned to give detailed answers
- Fewer empty responses means more reliable instruction following
""")

# per domain breakdown
domains = [
    "Indian culture & history",
    "General knowledge",
    "Everyday instructions",
    "Math reasoning",
    "Polite conversation"
]

print("PER-PROMPT COMPARISON (from Cell 9 prompts):")
print("-" * 70)
for i, (domain, base_r, ft_r) in enumerate(zip(domains, base_responses, ft_responses)):
    base_words = len(base_r.split())
    ft_words   = len(ft_r.split())
    print(f"{i+1}. {domain}")
    print(f"   Base: {base_words} words | Fine-tuned: {ft_words} words")
print("=" * 70)

